version: '3.4'

services:
  tests:
    build:
      context: ../
      dockerfile: .ops/docker/app/Dockerfile
      target: golang
    container_name: tests
    volumes:
      - "../:/go/src/app"
    working_dir: /go/src/app
    command: >
      sh -c "go test -v -failfast -covermode=count -coverprofile=coverage.out ./..."
networks:
  default:
    external:
      name: ${NETWORK}
