name: Build
on:
  push:
    branches:
      - master
      - develop
      - '*.*.*'
  pull_request:
jobs:
  analyze:
    name: Static Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Static Analysis
        run: make analyze
  test:
    name: Test
    needs: analyze
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: make test
      - name: Check Coverage
        run: make coverage
  release:
    name:  Release
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      RELEASE_VERSION: ~
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        run: |
          docker run --rm -e GITHUB_TOKEN=${GITHUB_TOKEN} -v "${PWD}":/app michcald/semantic-release
          if test -f .RELEASE_VERSION; then
            release_version="$(cat .RELEASE_VERSION)"
            echo "::set-env name=RELEASE_VERSION::$release_version"
          fi
